#!/usr/bin/env python

import json
import requests
url = 'http://dev.websiteonline.website/saveSingleObservation'
data = {'current_observation': {'temp_f':32}}   
headers = {'Content-type': 'application/json','Accept': 'text/plain'}
r = requests.post(url, data = json.dumps(data), headers = headers)
print r
