#!/usr/bin/env python

import json
import requests
url = 'http://dev.websiteonline.website/saveSensorData'
data = {'tempF': 1,'poop':32}
headers = {'Content-type': 'application/json','Accept': 'text/plain'}
r = requests.get(url, data = json.dumps(data), headers = headers)
print r
